version: '3.7'

services:
  postgres:
    image: 'postgres:14.5'
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_dB: fiber_web_api
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - webapi_network
    restart: unless-stopped
 
  redis:
    image: 'redis:8'
    container_name: redis_container
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - redis:/etc/redis/redis.conf
      - redis:/data
    ports:
      - "6379:6379"
    networks:
      - webapi_network

volumes:
 postgres:
 redis:
 logs:

networks:
 webapi_network:
  driver: bridge